name: instagram
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  dotted_border: ^2.1.0
  flutter_staggered_grid_view: ^0.6.2
  connectivity_plus: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

  uses-material-design: true

  assets:
    - assets/images/


  fonts:
    - family: GT
      fonts:
        - asset: assets/fonts/GilroyThin.ttf
          weight: 100

    - family: GL
      fonts:
        - asset: assets/fonts/GilroyLight.ttf
          weight: 300

    - family: GR
      fonts:
        - asset: assets/fonts/GilroyRegular.ttf
          weight: 400 

    - family: GM
      fonts:
        - asset: assets/fonts/GilroyMedium.ttf
          weight: 500                   

    - family: GB
      fonts:
        - asset: assets/fonts/GilroyBold.ttf
          weight: 700

    - family: GEB
      fonts:
        - asset: assets/fonts/GilroyExtraBold.ttf
          weight: 800

    - family: GH
      fonts:
        - asset: assets/fonts/GilroyHeavy.ttf
          weight: 900

  





  

        

    - family: SM
      fonts:
        - asset: assets/fonts/ShabnamMedium.ttf
          weight: 400

  
